### ISSUE TITLE
Please use our Bug Tracker at https://pp.info.uni-karlsruhe.de/joana-bugs/

### ISSUE THREAD

**Issue by jgf** [joana-team/joana#1]
We do not use the GitHub Bugtracker.
Please use this instead: https://pp.info.uni-karlsruhe.de/joana-bugs/
We may change the url to https://pp.ipd.kit.edu/joana-bugs/ when the ssl certificate has been updated.

**Comment by noilly** [comment]
Hi, neither of these URLs are available, i.e., receive 403 Forbidden
