### ISSUE TITLE
Clarify requirement of a g++ compiler to run setup_deps

### ISSUE THREAD

**Issue by Portals** [joana-team/joana#11]
Hello!

While trying to set up the project I ran into an issue where `com.ibm.wala.cast` didn't compile properly. After reading through the `mvn` output, I found out that I was missing a `g++` compiler. I think this needs to be clarified in `README.md`. 

With Ubuntu, I could retrieve a g++ compile with `sudo apt install build-essential`.

**Comment by parttimenerd** [comment]
Thanks for your comment. I did not know that.
If you work with Joana and have some questions, consider dropping us a mail.
